export const SET_CANDIDATES = 'SET_CANDIDATES'
export const VOTE_CANDIDATE = 'VOTE_CANDIDATE'
export const SET_INFORMATION = 'SET_INFORMATION'
export const SET_CANDIDATES_UNSUBSCRIBE = 'SET_CANDIDATES_UNSUBSCRIBE'